# Generated by Django 3.1 on 2020-08-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvProgram',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_genre', models.CharField(max_length=100)),
                ('t_title', models.TextField(default='')),
                ('t_info', models.TextField(default='')),
                ('t_age', models.IntegerField(default=0)),
                ('t_director', models.CharField(max_length=100)),
                ('t_season', models.IntegerField(default=0)),
                ('t_episode', models.IntegerField(default=1)),
                ('t_episode_title', models.TextField(default='')),
                ('t_time', models.IntegerField(default=0)),
                ('t_cast', models.TextField(default='')),
                ('t_date', models.DateField(default=0)),
                ('t_episode_info', models.TextField(default='')),
                ('t_file', models.TextField(default='')),
                ('t_request_date', models.DateField(auto_now_add=True)),
                ('t_state', models.IntegerField(default=0)),
                ('t_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
