# Generated by Django 3.1 on 2020-08-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProgram',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_genre', models.CharField(max_length=100)),
                ('m_title', models.TextField(default='')),
                ('m_info', models.TextField(default='')),
                ('m_age', models.IntegerField(default=0)),
                ('m_director', models.CharField(max_length=100)),
                ('m_time', models.IntegerField(default=0)),
                ('m_cast', models.TextField(default='')),
                ('m_date', models.DateField(default=0)),
                ('m_file', models.TextField(default='')),
                ('m_request_date', models.DateField(auto_now_add=True)),
                ('m_state', models.IntegerField(default=0)),
                ('m_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
